name = "vortex_interactive/scripts_core"
version = "0.2.1"
description = "Scripts and other utilities for use with pesde"
authors = [
  "daimond113 <contact@daimond113.com> (https://www.daimond113.com/)",
  "Erica Marigold <hi@devcomp.xyz>",
]
repository = "https://github.com/Vortex-Interactive/pesde-roblox-scripts"
license = "MIT"
includes = [
  "src/**/*.luau",
  "!src/**/*.spec.luau",
  "pesde.toml",
  "README.md",
  "LICENSE",
]

workspace_members = [".", "dist/*"]

[engines]
pesde = "^0.7.1"
lune = "^0.10.3"

[meta.scripts.rojo]
version = "0.2.1"
tool_dependencies = { rojo = { name = "vortex_interactive/rojo", version = "^7.5.1+toolchainlib.2" } }

[meta.scripts.argon]
version = "0.2.1"
tool_dependencies = { argon = { name = "vortex_interactive/argon", version = "^2.0.26+toolchainlib.2" } }

[target]
environment = "lune"
lib = "src/init.luau"

[dev_dependencies]
frktest = { name = "itsfrank/frktest", version = "^0.0.4", target = "luau", index = "official" }
pathfs = { name = "jiwonz/pathfs", version = "^0.6.0", index = "official" }
luau-lsp = { name = "vortex_interactive/luau_lsp", version = "^1.54.0+toolchainlib.2" }
stylua = { name = "vortex_interactive/stylua", version = "^2.3.0+toolchainlib.2" }
argon = { name = "vortex_interactive/argon", version = "^2.0.26+toolchainlib.2" }
rojo = { name = "vortex_interactive/rojo", version = "^7.5.1+toolchainlib.2" }

[indices]
default = "https://github.com/Vortex-Interactive/pesde-index"
official = "https://github.com/pesde-pkg/index"
